### ISSUE TITLE
Auto focus the share window?

### ISSUE THREAD

**Issue by guitarpoet** [mattt/terminal-share#5]
I wrote a little script to compose and send the share using your awesome terminal-share library.

Everything works so fine, only a small problem there, I must click the post button to send the share.

In the GUI environment, the share window is auto focused, and the post button is on the default button state. So I just need to hit Ctrl+Shift+D(the pretty old way to send), and the share message is sent.

But, when I start the share window using terminal-share in the iTerm2, the share window seems not focused, every key I typed is sending to the terminal.

Just like the screenshot here:
<img width="456" alt="sina_weibo" src="https://cloud.githubusercontent.com/assets/14401/17838023/f0a42d94-67f4-11e6-9d75-c58bb1d69c8d.png">

Is there any way to make it auto focused, so that I can send the share message using keyboard only.

**Comment by JayBrown** [comment]
The same behavior (sharing window in background) happens with iTerm2 and share to Apple Messages (Catalina 10.15.7).

**Comment by JayBrown** [comment]
There is a (possibly) related problem, in that the primary input field (in the primary float) doesn't work. The user must click on the (+) icon, but there text input in the "search contacts" field doesn't work either. What doesn't work either, is clicking on a Contact to select from their telephone numbers etc. The only workaround in the latter case is to **CMD-click** on the contact's name, and then, when selecting e.g. a telephone number, a normal click will suffice. But you won't get there with search text input, and you won't get there without CMD-click.
